# This is a basic workflow to help you get started with Actions

name: Test run

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test_unit:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with: 
          node-version: '14.x'
          
      - name: Install dependencies
        run: |
          npm install
          npm run build
          npm test
